### Obtener todas las especialidades
GET http://localhost:7000/especialidades

### Obtener especialidad por ID
GET http://localhost:7000/especialidades/1

### Agregar especialidad
POST http://localhost:7000/especialidades
Content-Type: application/json

{
    "nombreEspecialidad": "Cardiología"
}

### Actualizar especialidad
PUT http://localhost:7000/especialidades/1
Content-Type: application/json

{
    "idEspecialidad": 1,
    "nombreEspecialidad": "Cardiología Pediátrica"
}

### Eliminar especialidad
DELETE http://localhost:7000/especialidades/1
