spring.application.name=estadoTratamiento

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

spring.datasource.url=jdbc:mysql://localhost:3306/estado_tratamiento?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=6920

springdoc.swagger-ui.path=/estado-tratamiento.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.operationsSorter=alpha


app.name=Componente Estado Tratamiento
app.version=1.0.0