### Configuración de variables
@host = http://localhost:8083
@idProfesional = 1

### 1. Obtener todos los profesionales
GET {{host}}/profesionales
Accept: application/json

---

### 2. Obtener un profesional por ID
GET {{host}}/profesionales/{{idProfesional}}
Accept: application/json

---

### 3. Agregar un nuevo Profesional
# OJO: idUsuario e idEspecialidad deben existir en sus respectivos MS
POST {{host}}/profesionales
Content-Type: application/json

{
  "idUsuario": 1,
  "numeroRegistroProfesional": "123456-CH",
  "idEspecialidad": 2
}

---

### 4. Actualizar la especialidad de un profesional
# Según tu lógica, enviamos el registro médico (sin cambiarlo) y la nueva especialidad
PUT {{host}}/profesionales/{{idProfesional}}
Content-Type: application/json

{
  "numeroRegistroProfesional": "123456-CH",
  "idEspecialidad": 5
}

---

### 5. Eliminar un profesional
DELETE {{host}}/profesionales/{{idProfesional}}