### LISTAR:
GET http://localhost:8081/direcciones


### OBTENER:
GET http://localhost:8081/direcciones/1

### AGREGAR:
POST http://localhost:8081/direcciones
Content-Type: application/json

{
    "calleDireccion": "Avenida Costanera",
    "numeroDireccion": 500,
    "idComuna": 1
}


### ACTUALIZAR:
PUT http://localhost:8081/direcciones/1
Content-Type: application/json

{
    "idDireccion": 1,
    "calleDireccion": "Calle Modificada",
    "numeroDireccion": 999,
    "idComuna": 400
}

### ELIMINAR:
DELETE http://localhost:8081/direcciones/4