# Nombre del microservicio
spring.application.name=direccion

# Puerto diferente para evitar conflictos (usaremos el 8081)
server.port=8081

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always

# Conexión a BD (Mantenemos tu configuración de MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/full_Stack_3?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=jav_2026.@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect