### Variables de entorno (Puerto adaptado al microservicio usuarios en ejecución)
@url = http://localhost:7575/api/usuarios

### Obtener todos los usuarios
GET {{url}}/listar

### Agregar un nuevo Usuario / Administrador
# NOTA: Pendiente ajustar el mapeo del objeto 'direccion' con las validaciones del microservicio.
POST {{url}}/agregar
Content-Type: application/json

{
  "rutUsuario": "12445674-9",
  "pnombreUsuario": "Juan",
  "snombreUsuario": "Ignacio",
  "apaternoUsuario": "Perez",
  "amaternoUsuario": "Soto",
  "emailUsuario": "juan.perezxd@duoc.cl",
  "telefonoUsuario": "987654321",
  "contrasenaUsuario": "clave123",
  "fechaNacimientoUsuario": "1995-10-15",
  "activo": true,
  "idGenero": 1,
  "idRol": 2,
  "idDireccion": 1,
  "direccion": {
    "id": 1,
    "calle": "Av. Concha y Toro",
    "numero": 1234,
    "id_comuna": 1
  }
}

### Actualizar usuario (Cambia el /1 por el ID generado si es necesario)
PUT {{url}}/actualizar/1
Content-Type: application/json

{
  "rutUsuario": "12445674-9",
  "pnombreUsuario": "Juan",
  "snombreUsuario": "Ignacio",
  "apaternoUsuario": "Perez",
  "amaternoUsuario": "Gonzales",
  "emailUsuario": "j.perez.new@duoc.cl",
  "telefonoUsuario": "999888777",
  "contrasenaUsuario": "nuevaClave123",
  "fechaNacimientoUsuario": "1995-10-15",
  "activo": true,
  "idGenero": 1,
  "idDireccion": 1,
  "idRol": 2
}

### Eliminar usuario
DELETE {{url}}/eliminar/1