### Variables de entorno
@url = http://localhost:7575/usuarios

###Obtener todos los usuarios
GET {{url}}

###Obtener un usuario por ID (Cambia el 1 por uno que exista)
GET {{url}}/1

###Obtener usuario por RUT
GET {{url}}/rut/12345678-9

###Obtener usuario por Email
GET {{url}}/email/s.tapia@satmed.cl

### Este gatilla la orquestación con MS Direcciones, Género y Rol
POST {{url}}
Content-Type: application/json

{
    "pnombreUsuario": "Juan",
    "snombreUsuario": "Ignacio",
    "apaternoUsuario": "Perez",
    "amaternoUsuario": "Soto",
    "rutUsuario": "12445674-9",
    "emailUsuario": "juan.perezxd@duoc.cl",
    "telefonoUsuario": "987654321",
    "contrasenaUsuario": "clave123",
    "fechaNacimientoUsuario": "1995-10-15",
    "idGenero": 1,
    "idRol": 2,
    "calleDireccion": "Avenida Siempre Viva",
    "numeroDireccion": 742,
    "idComuna": 15
}

### Cambia el /1 por el ID que quieras editar
PUT {{url}}/1
Content-Type: application/json

{
    "pnombreUsuario": "Juan",
    "snombreUsuario": "Ignacio",
    "apaternoUsuario": "Perez",
    "amaternoUsuario": "Gonzales",
    "emailUsuario": "j.perez.new@duoc.cl",
    "telefonoUsuario": "999888777",
    "fechaNacimientoUsuario": "1995-10-15",
    "idGenero": 1,
    "contrasenaUsuario": "nuevaClave123",
    "idRol": 2,
    "calleDireccion": "Calle Falsa",
    "numeroDireccion": 123,
    "idComuna": 10
}

### Solo cambia el estado a 'false' en XAMPP
DELETE {{url}}/1