### ========================================
### REGIONES - SAT-MED
### ========================================

### Obtener todas las regiones
GET http://localhost:6200/regiones

### Obtener región por ID
GET http://localhost:6200/regiones/1


####
GET http://localhost:6200
