@api = http://localhost:6920/estado-tratamiento

### 1. Obtener todos los estados de tratamiento (Para el select de Angular)
GET {{api}}
Accept: application/json

---

### 2. Obtener un estado de tratamiento por ID (Por si lo necesitas)
GET {{api}}/1
Accept: application/json    