### ========================================
### COMUNA - SAT-MED
### ========================================

### Obtener todos los roles
GET http://localhost:6100/comunas

### Obtener rol por ID
GET http://localhost:6100/comunas/1 
